### ISSUE TITLE
Should we allow multiple individual agreements?

### ISSUE THREAD

**Issue by zdw** [OpenNetworkingFoundation/cla-manager#106]
Should a user who has signed an individual agreement be allowed to sign another separate agreeement, or only update their existing agreement?

**Comment by teone** [comment]
From the legal standpoint I don't think it makes any difference, but we should double-check with the lawyer.

**Comment by teone** [comment]
Closing this issue for now. It's not a real problem as long as a contributor is covered by an agreement of any kind.
