### ISSUE TITLE
Create "static" pages that show the most recent text of the CLA without login

### ISSUE THREAD

**Issue by zdw** [OpenNetworkingFoundation/cla-manager#107]
Add URLs to the CLA tool that show the most recent version of the CLA text without logging into the system. 

URL's would be something like:

    https://cla-manager.../agreements/individual
    https://cla-manager.../agreements/institutional

**Comment by bocon13** [comment]
We don't currently have a way to "show pages" in the CLA tool unless a user is logged in. There's a few ways we could solve this... but the gist of it is probably updating our React router to understand whether or not a user is signed in, and then using that to enforce what pages are / aren't shown if they aren't.

**Comment by bocon13** [comment]
Once the routing logic is taken care of, we should be able to reuse the AgreementDisplay or ReactMarkdown components to display the CLA the same way we do when we ask users to sign.
