### ISSUE TITLE
Create GH CLAM app

### ISSUE THREAD

**Issue by ccascone** [OpenNetworkingFoundation/cla-manager#11]

**Comment by hwchiu** [comment]
@zdw Do we have an official ONF GitHub account? I think we should create the app by the official account.

**Comment by hwchiu** [comment]
@bocon13 do you know the account infromation?

**Comment by ccascone** [comment]
@hwchiu do you have any update on this? I'm starting to work on the GitHub PR handling and I would like to start deploying the functions, for which we need a GitHub app ID...

**Comment by hwchiu** [comment]
@ccascone no, I still don't get the official GitHub account yet.

**Comment by ccascone** [comment]
The app has been created.
