### ISSUE TITLE
After adding identify, "Full Name" field is empty

### ISSUE THREAD

**Issue by daniele-moro** [OpenNetworkingFoundation/cla-manager#120]
After adding an identity (email or GitHub id), the field "Full Name" on the same page is empty, cannot be modified and fails the add of a new identity.
A refresh of the page solves the issue.

**Comment by teone** [comment]
@daniele-moro this should have fixed it: https://github.com/OpenNetworkingFoundation/cla-manager/pull/117

If so can you close the issue?

**Comment by daniele-moro** [comment]
I  confirm that it has been fixed. Thanks!
