### ISSUE TITLE
Add support for `Managers` in institutional CLA

### ISSUE THREAD

**Issue by teone** [OpenNetworkingFoundation/cla-manager#129]
for Institutional CLA, we have three targets:

1. The person (ONE per CLA) who signs the CLA - the signatory (Signatory is also a manager, see below)
2. The person(s) who "manage" the agreement in that they add/remove IDs - the manager(s). The signatory can designate manager(s) and a manager should also be able to designate other manager(s).
3. People who's IDs and part of the CLA - the contributor(s), they can only ask the signatory or manager to add/remove their IDs, but cannot do it themselves.

**Comment by ccascone** [comment]
in  previous design discussions, we have defined managers as "co-signers"

**Comment by aindermitte** [comment]
I think it is very important to understand that managers are NOT co-signers.  As far as I know, there is one signatory in professional contracts.

**Comment by teone** [comment]
Here's a short summary of what I'm planning to do:
- [ ] Add Mangers to an Agreement: added in the [feature/cla-managers](https://github.com/OpenNetworkingFoundation/cla-manager/tree/feature/cla-managers) branch
- [ ] Add a function that anytime an `Addendum` is created updates a `ManagerWhitelist` (similar to the `updateWhitelist` function we have now)
- [ ] Update the `firestore.rules => isManager` so that if a user is in the `ManagerWhitelist` for that `Agreement` he/she is allowed to create an addendum

**Comment by teone** [comment]
Confirmed in [this commit](https://github.com/OpenNetworkingFoundation/cla-manager/commit/e2c9d72aac9dbd536fce8b61d7e4a55f325d5f57) that this a viable solution
