### ISSUE TITLE
Trigger deployment to firebase via circle CI

### ISSUE THREAD

**Issue by ccascone** [OpenNetworkingFoundation/cla-manager#13]

**Comment by teone** [comment]
For the frontend you need to run `npm run build` that will generate a `build` folder that contains all the files that need to be uploaded to firebase

**Comment by teone** [comment]
Also noticed that to deploy the `functions` we need to:
```
firebase --project <name> functions:config:set github.app_id="APP_ID" github.key="KEY" github.secret="SECRET"
```
before running `firebase --project <name> deploy`

**Comment by hwchiu** [comment]
@teone 
I met the [error](https://circleci.com/gh/bocon13/cla-manager/47) when I try to use the firebase to deploy the `client`, what is the `app_id`, is it github.app_id?

**Comment by ccascone** [comment]
@hwchiu that errror is triggered when deploying `functions`, not `client`. You have to pass the extra arguments as suiggested by teo above

**Comment by hwchiu** [comment]
@ccascone 
I run the command `firebase --project <project-id> deploy` under the `client` directory. it will also upload functions?

**Comment by hwchiu** [comment]
ok, it works by adding this argument `--only firestore`

**Comment by ccascone** [comment]
@hwchiu, that command deploys everything. In this case it looks for file `firebase.json` in the project top-level directory

**Comment by teone** [comment]
before deploying the client we need to run
```
REACT_APP_FIREBASE_ENV=<project-name> REACT_APP_FIREBASE_API_KEY=<firebase-api-key> npm run build
```

**Comment by hwchiu** [comment]
Support client now will do the `functions` once the #11 be resolved.

**Comment by hwchiu** [comment]
Done
