### ISSUE TITLE
Clicking "back" on the agreement page brings to the CLAM home

### ISSUE THREAD

**Issue by ccascone** [OpenNetworkingFoundation/cla-manager#139]
When viewing agreements as an admin, when clicking "black" it should bring to the previous page, i.e. the agreement or identities list

**Comment by teone** [comment]
Interesting, which browser are you using? I see it working as expected on Opera

**Comment by ccascone** [comment]
I use Safari. I realize my explanation might be ambiguous so here's a demo of the issue:
![Mar-26-2020 22-21-17](https://user-images.githubusercontent.com/3025473/77724463-445b9000-6fb0-11ea-976a-98db3d79365f.gif)
