### ISSUE TITLE
Define JSON structure for cla-verify request/response

### ISSUE THREAD

**Issue by ccascone** [OpenNetworkingFoundation/cla-manager#14]

**Comment by ccascone** [comment]
Request examples:
https://github.com/bocon13/cla-manager/blob/master/functions/test/fixtures/pull_request.opened.huge.json
https://github.com/bocon13/cla-manager/blob/master/functions/test/fixtures/pull_request.opened.json

**Comment by ccascone** [comment]
Response
```
{
  signed: [true|false],
  message: [string]
}
``

**Comment by zdw** [comment]
On `singed: false`, the message would contain information and a link to sign the CLA.  

Eventually the link URL could be parameterize with the email, username, etc.

**Comment by zdw** [comment]
Looking at the JSON examples further the user information seems like it's in two places - the actual pull request and the sender.  As the sender is simpler to parse, should the request should look something like this? 
```
{
...
        "action": "opened",
        "sender": {
                "login": "github_user_id",
                "email": "email_address"
        }
...
}
```
