### ISSUE TITLE
Integrate with remote javascript error/log reporting

### ISSUE THREAD

**Issue by ccascone** [OpenNetworkingFoundation/cla-manager#15]
For example, Bugsnag (so we can track down exceptions with requests)

**Comment by ccascone** [comment]
Or use, whatever is provided by Firebase

**Comment by teone** [comment]
I think we can close this as firebase stores the log for us (at least the function logs)

**Comment by ccascone** [comment]
Debugging function logs from the firebase UI is not the best experience. I like bugnsnag as it gives more context, including showing the code that produced the error, the request parameters, etc. Maybe we can target this for v2

**Comment by ccascone** [comment]
Just noticed of this error in the browser console after deploying #62 
```
TypeError: Agreement.type is corporate and organizationAddress is missing — 
```

The fix for this one is to delete my old agreements, but...

Without a system like Bugsnag, do we have a way to get notified and track client errors like this? If not, I think we should promote this issue to `blocker` level, otherwise debugging user errors gets much harder...

**Comment by teone** [comment]
@ccascone I'm totally fine with bugsnag, for now I think we can get away with the free plan.

**Comment by ccascone** [comment]
#94 adds Bugsnag to the client. I removed the `v2` label as I think we need this ASAP, for example to catch DB permission errors.

**Comment by teone** [comment]
I believe this is resolved, please reopen if not true
