### ISSUE TITLE
CLA signature date error

### ISSUE THREAD

**Issue by teone** [OpenNetworkingFoundation/cla-manager#156]
**Describe the bug**
When I look at CLA agreements, I always see the signing date/time as current date/time.  For example, Radisys agreement that I looked was signed yesterday, today shows today's date.

**Expected behavior**
See the actual date of when the CLA was signed

**Screenshots**
![unnamed](https://user-images.githubusercontent.com/3929466/80527420-2edbdc00-8949-11ea-9131-e92d7c302cf3.png)

**Comment by zdw** [comment]
I encountered this as well - if I go into the agreement details page, it says `We have 10 addendums on file for this agreement. The last one was signed on: Mon Jun 15 2020 11:23:51 GMT-0700 (Mountain Standard Time)`, and that time updates with the current time every time the pages are reloaded.
