### ISSUE TITLE
If the user erroneously enter a whitespace in the identity PR validation fails

### ISSUE THREAD

**Issue by teone** [OpenNetworkingFoundation/cla-manager#213]
**Describe the bug**
A user as added a GitHub ID with a final whitespace to a CLA and the PR validation was failing.

**Expected behavior**
Trim whitespaces when:
- saving an addendum
- reconciling the whitelist

**Comment by aindermitte** [comment]
Make sure to do this also for the leading spaces, not just the trailing ones.
Also, might be related, but some people are claiming they cannot start the email or GitHub ID with lowercase, it always forces uppercase.  What could be the cause of that?
In my setup (PC, Windows10, Chrome), I have no problem of entering lowercase characters to start the email or ID.

**Comment by teone** [comment]
@aindermitte I am not sure about the lowercase, I haven't had any issue with that. I tried it from Mac with Chrome, Firefox, Opera and Safari and couldn't replicate.

By any chance could you try with Explorer/Edge?

Regardless that's not an issue as in the backend all the identities are treated as lowercase, so it's only a visualization thing.

**Comment by aindermitte** [comment]
@teone no problem on Edge either.  I suspect that it was this particular person's local browser or text input settings.  I was on the call with him and saw how he tried to enter the text and couldn't figure out how to lowercase it.  I didn't notice him adding the extra space in the end, but that could have also been an automatic setting, who knows.  He didn't seem very tech-savvy person.
