### ISSUE TITLE
Database backup

### ISSUE THREAD

**Issue by teone** [OpenNetworkingFoundation/cla-manager#27]

**Comment by hwchiu** [comment]
Since we changed to Blaze paid plane, we can use the automatic backup function they provided.
https://console.firebase.google.com/project/cla-manager-f1a7f/database/backups

**Comment by ccascone** [comment]
@hwchiu I might be wrong but it looks like the automatic back is for Realtime Database, not Firestore. We use the latter, but I can't see any automatic backup feature for that. Have you checked the content of the backups?

**Comment by hwchiu** [comment]
@ccascone, you're right, I will check other approaches to see how to backup the database

**Comment by hwchiu** [comment]
According to this [document](https://firebase.google.com/docs/firestore/manage-data/export-import),  we can use the command `gcloud firestore  export/import` the data between firestore and google storage bucket.

**Comment by bocon13** [comment]
https://firebase.google.com/docs/firestore/solutions/schedule-export

**Comment by ccascone** [comment]
MVP is:
- Daily snaphost on gcloud storage
Nice to have:
- Restore procedure
- Run before upgrades
- Copy over AWS or some other place

**Comment by hwchiu** [comment]
Copy from GS to AWS s3: https://stackoverflow.com/questions/39329580/exporting-data-from-google-cloud-storage-to-amazon-s3
