### ISSUE TITLE
When signing as an individual there should be no need to ask for a name

### ISSUE THREAD

**Issue by ccascone** [OpenNetworkingFoundation/cla-manager#35]
The name can be derived from the agreement signer. The UI should show an input field for the email and/or githubID, but not for the name.
![Screen Shot 2020-02-03 at 1 32 49 PM](https://user-images.githubusercontent.com/3025473/73693085-6dcffd80-468a-11ea-9d93-9b961fac340f.png)

**Comment by teone** [comment]
The `name` field is to identify the `Identity`, I think it still make sense in case of:
- `{name: "personal-github", value: "teone"}`
- `{name: "work-github", value: "teo-onf"}`

We could change the label to `description` if that fits better the usage

**Comment by ccascone** [comment]
If that's the case then we should have both fields `name` and `description`. Where the former is a person full name, and the latter is what you described above. This way, for individual agreements, the `name` should be auto-populated, while for corporate ones it should be part of the form presented to the addendum signer. What do you think?

**Comment by teone** [comment]
what is the need to separate them?
the only thing we really care about is the `value` field, everything else is a plus for the user convenience, and I think we can live with a single descriptive field for now

**Comment by ccascone** [comment]
For corporate CLAs we need to collect `name`s, for individual ones it would be nice to collect a `description`
