### ISSUE TITLE
Review DB access rules

### ISSUE THREAD

**Issue by teone** [OpenNetworkingFoundation/cla-manager#49]

**Comment by teone** [comment]
@bocon13 @hwchiu can you take care of this?

**Comment by ccascone** [comment]
Review rules for:
- agreement (create/read by the signer, no update/delete)

Create signer-dependent rules:
- addendums (create/read by signer of parent agreement, no update/delete)

The following should be accessible by admin only:
- contributions
- events
- whitelists

**Comment by ccascone** [comment]
https://firebase.google.com/docs/firestore/security/test-rules-emulator
