### ISSUE TITLE
Set domain for outgoing emails

### ISSUE THREAD

**Issue by ccascone** [OpenNetworkingFoundation/cla-manager#57]
Sign in emails are sent from a firebase-specific email address `noreply@cla-manager-f1a7f.firebaseapp.com`. It would be preferable for them to come from an ONF address, such as   `noreply@cla.opennetworking.org`. This can be changed in the firebase project configuration: https://console.firebase.google.com/u/0/project/cla-manager-f1a7f/authentication/emails

**Comment by hwchiu** [comment]
Added the DNS record for verification.
It can take up to 48 hours to verify your domain. Check back later to finish adding your custom domain.

**Comment by hwchiu** [comment]
Done
