### ISSUE TITLE
Add auth mechanism for Gerrit hook

### ISSUE THREAD

**Issue by ccascone** [OpenNetworkingFoundation/cla-manager#61]
Such that we can ignore calls coming from unauthorized sources.

We agreed with @zdw to use HTTP basic auth, as long as the secret is configured using Firebase config via CI (exactly as we do for github secrets)

**Comment by ccascone** [comment]
@zdw is you can work on the python script, I can add it to the function serving the HTTP requests.

**Comment by zdw** [comment]
Sure, I can do this. Is there a good way to test this locally?

**Comment by ccascone** [comment]
Not sure... maybe you can use node to start an HTTP server as we do for the functions unit tests: https://github.com/OpenNetworkingFoundation/cla-manager/blob/master/functions/test/gerrit.test.js

**Comment by ccascone** [comment]
Added support for checking auth headers in #63 

I've set the username and password as firebase configs. To retrieve their values you can use the firebase CLI command:

```
firebase --project cla-manager-f1a7f functions:config:get
```

**Comment by zdw** [comment]
Done in #63 and #119
