### ISSUE TITLE
Allow users to show agreements they are associated with

### ISSUE THREAD

**Issue by ccascone** [OpenNetworkingFoundation/cla-manager#65]

**Comment by teone** [comment]
This feature is more complex than it can seem at first sight.
It's easy to show people an agreement on which they're included with the email they use to login, the tool does not know the other identities that can exists.

For example, if I login as `teo@opennetworking.org` it's easy to find the agreements in which that email address is listed, but we have no way to track down the ones on which I'm listed a `github:teone`

**Comment by teone** [comment]
Duplicated by #150
