### ISSUE TITLE
Implement Gerrit hook

### ISSUE THREAD

**Issue by ccascone** [OpenNetworkingFoundation/cla-manager#7]

**Comment by zdw** [comment]
In progress: https://github.com/zdw/cla-manager/tree/gerrit

**Comment by ccascone** [comment]
I'm starting to add support for the Gerrit hook in the functions. The current approach where we use a URI get parameter to pass an identity works fine as a start, but we should consider some level of authorization, e.g. by using JWT: https://jwt.io

**Comment by zdw** [comment]
Agreed on the auth.  In the hook I actively avoided 3rd party libraries installed from PyPI, to simplify deployment, which JWT seems to require. 

Is there a way to run an instance of the server locally for API testing?

**Comment by ccascone** [comment]
Closing this. Will open a new one to implement an auth mechanism.
