### ISSUE TITLE
When clicking twice on "Sign Addendum" identities get added twice

### ISSUE THREAD

**Issue by ccascone** [OpenNetworkingFoundation/cla-manager#91]
I clicked once and nothing happened on the UI, so  I clicked again. After a few seconds,
 two identical identities showed up. Perhaps the "Sign Addendum" button should be disabled until the operation completes.

<img width="845" alt="Screen Shot 2020-02-12 at 5 31 38 PM" src="https://user-images.githubusercontent.com/3025473/74393062-ce171b80-4dbd-11ea-86f0-a0f19e7d923c.png">

**Comment by teone** [comment]
Agreed
