### ISSUE TITLE
On the Portal home page - there is nothing to explain the abbreviation CLA or what the agreement is

### ISSUE THREAD

**Issue by SeanCondon** [OpenNetworkingFoundation/cla-manager#93]
On https://cla.opennetworking.org/

Neither is there any link to any help page to describe why it is needed or what it is about.

The image for ONF does not link anywhere.

It might be a good idea to run it past marketing, or developer relations people.

**Comment by ccascone** [comment]
Partially fixed in #108 and deployed. Please take a look at https://cla.opennetworking.org/

The ONF image does not have a link yet.

**Comment by SeanCondon** [comment]
Looks much better, thanks
